#!/usr/bin/env node
// Generated by LiveScript 1.3.1
(function(){
  var Promise, exec, uid, _module;
  Promise = require('bluebird');
  exec = require('shelljs').exec;
  uid = require('uid');
  _module = function(){
    var process, iface;
    process = function(block, opts){
      var defaultIsSvg, targets;
      defaultIsSvg = {
        cmd: function(block, tmpFile, tmpDir, params){
          block.to(tmpDir + "/" + tmpFile + ".dot");
          return "dot -Tsvg " + params + " " + tmpDir + "/" + tmpFile + ".dot";
        },
        output: function(tmpFile, tmpDir, output){
          return output;
        }
      };
      targets = {
        'default': defaultIsSvg,
        svg: defaultIsSvg,
        png: {
          cmd: function(block, tmpFile, tmpDir, params){
            block.to(tmpDir + "/" + tmpFile + ".dot");
            return "dot -Tpng " + params + " " + tmpDir + "/" + tmpFile + ".dot | base64";
          },
          output: function(tmpFile, tmpDir, output){
            return '\n <img class="exemd--diagram exemd--diagram__dot" src="data:image/png;base64,' + output + '" /> \n';
          }
        }
      };
      return opts.pluginTemplate(targets, block, opts);
    };
    iface = {
      process: process
    };
    return iface;
  };
  module.exports = _module();
}).call(this);
