#!/usr/bin/env node
// Generated by LiveScript 1.3.1
(function(){
  "use strict";
  var Promise, exec, uid, debug, cwd, _module, join$ = [].join;
  Promise = require('bluebird');
  exec = require('shelljs').exec;
  uid = require('uid');
  debug = require("debug")("exemd-dot");
  cwd = process.cwd();
  _module = function(){
    var picNum, process, iface;
    picNum = 0;
    process = function(block, opts){
      var defaultIsSvg, targets;
      defaultIsSvg = {
        cmd: function(block, tmpFile, tmpDir, params){
          block.to(tmpDir + "/" + tmpFile + ".dot");
          return "dot -Tsvg " + params + " '" + tmpDir + "/" + tmpFile + ".dot'";
        },
        output: function(tmpFile, tmpDir, output){
          return output;
        }
      };
      targets = {
        'default': defaultIsSvg,
        svg: defaultIsSvg,
        png: {
          cmd: function(block, tmpFile, tmpDir, params){
            block.to(tmpDir + "/" + tmpFile + ".dot");
            return "dot -Tpng " + params + " '" + tmpDir + "/" + tmpFile + ".dot' | base64";
          },
          output: function(tmpFile, tmpDir, output){
            return '\n <img class="exemd--diagram exemd--diagram__dot" src="data:image/png;base64,' + output + '" /> \n';
          }
        },
        pdf: {
          cmd: function(block, tmpFile, tmpDir, params){
            var cc;
            debug("invoked");
            block.to(tmpDir + "/" + tmpFile + ".dot");
            cc = ["dot -Tsvg " + params + " '" + tmpDir + "/" + tmpFile + ".dot' > '" + tmpDir + "/" + tmpFile + ".svg'", "mkdir -p '" + cwd + "/figures'", "cat '" + tmpDir + "/" + tmpFile + ".svg' | rsvg-convert -z 0.5 -f pdf > '" + cwd + "/figures/f-dot-" + picNum + ".pdf'", "echo '" + cwd + "/figures/f-dot-" + picNum + ".pdf'"];
            picNum = picNum + 1;
            return join$.call(cc, ' && ');
          },
          output: function(tmpFile, tmpDir, output){
            var fname;
            fname = output;
            return "![](" + fname + ")";
          }
        }
      };
      return opts.pluginTemplate(targets, block, opts);
    };
    iface = {
      process: process
    };
    return iface;
  };
  module.exports = _module();
}).call(this);
