# Makefile autogenerated by Dyi on March 19, 2015
#
# Main target: all
# Sources:  src/index.js  ./verbfile.js 

.DEFAULT_GOAL := all


.PHONY: c-6jt51vxw
c-6jt51vxw: lib/index.js


.PHONY: c-6sopwn95
c-6sopwn95: readme.md


.PHONY: build
build: c-6jt51vxw c-6sopwn95


.PHONY: update
update: k-lcdyxon9


.PHONY: major
major: k-lefua7b1 k-u0rqcg5d


.PHONY: minor
minor: k-7u691pf0 k-diwxasfd


.PHONY: patch
patch: k-vlr6ltya k-aslxhtmg


.PHONY: prepare
prepare: lib .




.PHONY: k-m5cj3b11
k-m5cj3b11:  
	cp ./lib/index.js ./index.js


.PHONY: all
all: 
	make build 
	make k-m5cj3b11  


.PHONY: k-lcdyxon9
k-lcdyxon9:  
	make clean && ./node_modules/.bin/babel configure.js | node


.PHONY: k-lefua7b1
k-lefua7b1:  
	make all


.PHONY: k-u0rqcg5d
k-u0rqcg5d:  
	./node_modules/.bin/xyz -i major


.PHONY: k-7u691pf0
k-7u691pf0:  
	make all


.PHONY: k-diwxasfd
k-diwxasfd:  
	./node_modules/.bin/xyz -i minor


.PHONY: k-vlr6ltya
k-vlr6ltya:  
	make all


.PHONY: k-aslxhtmg
k-aslxhtmg:  
	./node_modules/.bin/xyz -i patch


.PHONY: clean
clean:  
	rm -f lib/index.js
	rm -f readme.md




lib/index.js: src/index.js 
	./node_modules/.bin/babel src/index.js -o ./lib/index.js

readme.md: ./verbfile.js docs/description.md docs/readme.md 
	./node_modules/.bin/verb

lib: 
	mkdir -p lib

.: 
	mkdir -p .

