# Makefile autogenerated by Dyi on March 19, 2015
#
# Main target: all
# Sources:  src/index.js  src/test.js  ./verbfile.js 

.DEFAULT_GOAL := all


.PHONY: c-wdi04ya2
c-wdi04ya2: lib/index.js lib/test.js


.PHONY: c-e7djww5o
c-e7djww5o: readme.md


.PHONY: build
build: c-wdi04ya2 c-e7djww5o


.PHONY: test
test: k-koarcqbi


.PHONY: docs
docs: k-7ewysrwt


.PHONY: update
update: k-01q50vt8


.PHONY: major
major: k-mfiu9lil k-03thy6nu


.PHONY: minor
minor: k-f3n3nf0d k-nsdbvwma


.PHONY: patch
patch: k-ha0luojr k-mwxdn9x2


.PHONY: prepare
prepare: lib .




.PHONY: k-l5l87nv3
k-l5l87nv3:  
	cp ./lib/index.js ./index.js


.PHONY: k-6u4f6yue
k-6u4f6yue:  
	make test


.PHONY: all
all: 
	make build 
	make k-l5l87nv3 
	make k-6u4f6yue  


.PHONY: k-koarcqbi
k-koarcqbi:  
	./node_modules/.bin/mocha ./lib/test.js


.PHONY: k-7ewysrwt
k-7ewysrwt:  
	dot -Tpng src/source.dot > docs/exemd-dot.png


.PHONY: k-01q50vt8
k-01q50vt8:  
	make clean && ./node_modules/.bin/babel configure.js | node


.PHONY: k-mfiu9lil
k-mfiu9lil:  
	make all


.PHONY: k-03thy6nu
k-03thy6nu:  
	./node_modules/.bin/xyz -i major


.PHONY: k-f3n3nf0d
k-f3n3nf0d:  
	make all


.PHONY: k-nsdbvwma
k-nsdbvwma:  
	./node_modules/.bin/xyz -i minor


.PHONY: k-ha0luojr
k-ha0luojr:  
	make all


.PHONY: k-mwxdn9x2
k-mwxdn9x2:  
	./node_modules/.bin/xyz -i patch


.PHONY: clean
clean:  
	rm -f lib/index.js
	rm -f lib/test.js
	rm -f readme.md




lib/index.js: src/index.js 
	./node_modules/.bin/babel src/index.js -o ./lib/index.js

lib/test.js: src/test.js 
	./node_modules/.bin/babel src/test.js -o ./lib/test.js

readme.md: ./verbfile.js docs/description.md docs/readme.md 
	./node_modules/.bin/verb

lib: 
	mkdir -p lib

.: 
	mkdir -p .

